spring:
  datasource:
    url: jdbc:postgresql://db-postgres:5432/EXIT8
    username: exit8
    password: exit8pass
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: db-redis
      port: 6379
